#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvpsကိုroot အနေနဲ့ run ရပါမယ်\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mကျေးဇူးပြုရင်စောင့်ပါ \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mကျေးဇူးပြုရင်စောင့်ပါ \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
  echo -e "\n\033[1;31mမမှန်ကန်သောဖိုင်စာရင်း!\033[0m"
  rm -rf $HOME/Plus > /dev/null 2>&1
  sleep 2
  clear; exit 1
}
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "GAMERVPN SCRIPT BY JUEHTET" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "             \033[1;31mသတိပေးချက်! \033[1;33mScript ကိုတစ်ကြိမ်ထက်ပို၍ထည့်သွင်းခြင်းသည်သင်၏ VPS ကိုပျက်စီးစေနိုင်သည်!\033[0m"
echo ""
echo -e "\033[1;31m•\033[1;33mကိရိယာများအဖြစ် Script အစုံကိုထည့်သွင်းပါ\033[0m" 
echo -e "\033[1;33mကွန်ရက်စနစ်နှင့်အသုံးပြုသူစီမံခန့်ခွဲမှုအတွက်\033[0m"
echo ""
echo -e "\033[1;32m•\033[1;32mအကြံပြုချက်! \033[1;33mသင်၏ Terminal တွင်မှောင်မိုက်သောပုံစံကိုသုံးပါ\033[0m"
echo -e "\033[1;33mပိုမိုကောင်းမွန်သောအတွေ့အကြုံနှင့်တူညီသောအမြင်အာရုံ!\033[0m"
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×≠×[\033[1;33m•\033[1;32mBY Ta Tha Na VPN\033[1;33m•\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×≠×\033[0m"
echo ""
read -p "$(echo -e "\033[1;36mဆက်လုပ်ရန်ဆန္ဒရှိပါသလား \033[1;31m? \033[1;33m[s/n]:\033[1;37m ")" -e -i s resp
[[ $resp = @(n|N) ]] && rm $HOME/Plus && exit 0
_lnk2=$(echo "$key"|awk -F : '{print $2}'); _lnk1=$(echo "$key"|awk -F : '{print $1}')
echo -e "\n\033[1;36mစစ်ဆေးခြင်း... \033[1;37m File list\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://shwelu.000webhostapp.com/tathana-script/Install/list > /dev/null 2>&1; verif_key
echo -e "\n\033[1;32mတရားဝင်ဖိုင်စာရင်း!\033[1;32m"
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
    clear
    echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	echo -e "                 \033[1;33m• \033[1;31mသတိပေးချက် \033[1;33m• \033[0m"
	echo ""
    echo -e "\033[1;33mအသုံးပြုသူဒေတာဘေ့စ် \033[1;32m(user.db) \033[1;33mFoi" 
    echo -e "တွေ့ပြီ!  နယ်နိမိတ်ကို ထိန်းသိမ်းစောင့်ရှောက်လိုပါသလား"
	echo -e "တပြိုင်နက်တည်း အသုံးပြုသူချိတ်ဆက်မှုများ ?  ဒါမှမဟုတ် လိုချင်တယ်။"
    echo -e "ဒေတာဘေ့စ်အသစ်တစ်ခုဖန်တီးပါ။ ?\033[0m"
	echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mလက်ရှိဒေတာဘေ့စ်ကိုသိမ်းဆည်းပါ\033[0m"
	echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mဒေတာဘေ့စ်အသစ်တစ်ခုဖန်တီးပါ\033[0m"
	echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	tput setaf 2 ; tput bold ; read -p "Opção ?: " -e -i 1 optiondb ; tput sgr0
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "တပ်ဆင်ခြင်းကို စောင့်ပါ" ; tput sgr0
echo ""
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mအပ်ဒိတ်စနစ် \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "    \033[1;33mအပ်ဒိတ်များအချိန်ကြာပါမည်!\033[0m"
echo ""
fun_attlist () {
    apt-get update -y
	[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
	echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mPackages တပ်ဆင်ခြင်း \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33mအချို့သောပက်ကေ့ခ်ျများသည်အလွန်လိုအပ်ပါသည်!\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
for _prog in ${_pacotes[@]}; do
    apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mပြီးပါပြီ\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "      \033[1;33mလုပ်ဆောင်ချက်များနှင့်အဓိပ္ပါယ်ဖွင့်ဆိုချက်များပြီးမြောက်ခြင်း! \033[0m"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
rm -rf $HOME/systemverify* > /dev/null 2>&1; bash <(wget -qO- https://shwelu.000webhostapp.com/tathana-script/Install/systemverify)
clear
echo ""
cd $HOME
echo -e "        \033[1;33m•\033[1;32mတပ်ဆင်ခြင်းပြီးပါပြီ\033[1;33m•\033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mပင်မအမိန့်: \033[1;32mmenu\033[0m"
echo -e "\033[1;33m နောက်ထပ်အချက်အလက်များ \033[1;31m(\033[1;36mFacebook By\033[1;31m): \033[1;37mJueHtet\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
